import React from "react"

export default function FraudDetection() {
  return (
    <div className="relative min-h-screen bg-[#0a0814] text-white px-8 py-10">

      {/* Header */}
      <div className="mb-10">
        <h2 className="text-3xl font-bold">
          Fraud & Anomaly Detection
        </h2>
        <p className="mt-1 text-gray-400 max-w-2xl">
          Automated detection of suspicious patterns, inconsistencies, and
          adversarial fraud signals during loan assessment.
        </p>
      </div>

      {/* Main Grid */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">

        {/* Identity & Document Checks */}
        <div className="rounded-2xl bg-white/5 backdrop-blur-xl border border-white/10 p-6">
          <p className="text-xs uppercase tracking-wider text-gray-500 mb-4">
            Identity & Document Checks
          </p>

          <ul className="space-y-4 text-sm">
            <li className="flex justify-between">
              <span className="text-gray-300">KYC Match</span>
              <span className="text-emerald-400">Verified</span>
            </li>

            <li className="flex justify-between">
              <span className="text-gray-300">Document Tampering</span>
              <span className="text-emerald-400">Not Detected</span>
            </li>

            <li className="flex justify-between">
              <span className="text-gray-300">Synthetic Identity Risk</span>
              <span className="text-purple-300">Low</span>
            </li>
          </ul>
        </div>

        {/* Behavioural & Financial Anomalies */}
        <div className="rounded-2xl bg-white/5 backdrop-blur-xl border border-white/10 p-6">
          <p className="text-xs uppercase tracking-wider text-gray-500 mb-4">
            Behavioural & Financial Anomalies
          </p>

          <ul className="space-y-4 text-sm">
            <li className="flex justify-between">
              <span className="text-gray-300">Income Consistency</span>
              <span className="text-yellow-400">Minor Mismatch</span>
            </li>

            <li className="flex justify-between">
              <span className="text-gray-300">Cash Flow Stability</span>
              <span className="text-emerald-400">Stable</span>
            </li>

            <li className="flex justify-between">
              <span className="text-gray-300">Transaction Spikes</span>
              <span className="text-purple-300">Normal Range</span>
            </li>
          </ul>
        </div>

        {/* Network & Loan Stacking */}
        <div className="rounded-2xl bg-white/5 backdrop-blur-xl border border-white/10 p-6">
          <p className="text-xs uppercase tracking-wider text-gray-500 mb-4">
            Network & Loan Stacking
          </p>

          <ul className="space-y-4 text-sm">
            <li className="flex justify-between">
              <span className="text-gray-300">Multiple Active Loans</span>
              <span className="text-yellow-400">Detected</span>
            </li>

            <li className="flex justify-between">
              <span className="text-gray-300">Rapid Loan Applications</span>
              <span className="text-emerald-400">No</span>
            </li>

            <li className="flex justify-between">
              <span className="text-gray-300">Device / IP Reuse</span>
              <span className="text-purple-300">Low Risk</span>
            </li>
          </ul>
        </div>
      </div>

      {/* Decision Section */}
      <div className="mt-12 rounded-2xl bg-gradient-to-r from-purple-600/20 to-indigo-600/10 border border-purple-500/20 p-6 max-w-4xl">
        <h3 className="text-lg font-semibold mb-2">
          Fraud Risk Assessment Outcome
        </h3>

        <p className="text-gray-300 text-sm">
          Mild anomalies detected that do not indicate intentional fraud.
          Application is suitable for approval with enhanced monitoring or
          optional manual review.
        </p>

        <div className="mt-4 flex items-center gap-4">
          <span className="px-4 py-1 rounded-full text-sm bg-emerald-500/20 text-emerald-400">
            Risk Level: Low–Moderate
          </span>

          <span className="px-4 py-1 rounded-full text-sm bg-purple-500/20 text-purple-300">
            Recommendation: Conditional Approval
          </span>
        </div>
      </div>

      {/* Footer Note */}
      <div className="mt-10 text-sm text-gray-500 max-w-3xl">
        Fraud signals are identified using adversarial pattern detection,
        anomaly scoring, and behavioural consistency checks. In production,
        these signals would be generated by machine learning models trained
        on historical fraud patterns and evolving attack vectors.
      </div>

    </div>
  )
}
